# Generated by Django 4.1.2 on 2022-10-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Neopet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("species", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("temperament", models.CharField(max_length=30)),
            ],
        ),
    ]
