# Generated by Django 4.1.2 on 2022-10-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_toy_feeding_neopet_toys"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feeding",
            options={"ordering": ["-date"]},
        ),
    ]
