# Generated by Django 4.1.2 on 2022-10-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_toy_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="toy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.toy",
            ),
            preserve_default=False,
        ),
    ]
